In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('./data.csv')

In [4]:
display(data)

         step  id  left_child  right_child  warning  contaminated  active
0           2   1         999          999        0             0       1
1           3   1         999          999        0             0       1
2           4   7         999          999        0             0       1
3           4   8         999          999        0             0       1
4           4   3           7            8        0             0       1
...       ...  ..         ...          ...      ...           ...     ...
112925  14119   2           3          999        0             0       1
112926  14119   5         999          999        0             0       1
112927  14119   6         999          999        0             0       1
112928  14119   4           5            6        0             0       1
112929  14119   1           2            4        0             0       1

[112930 rows x 7 columns]